hosts:
  - name: router
    tcp: 192.168.1.1:80
    ping: 192.168.1.1

  - name: baidu
    ping: www.baidu.com
    tcp:  www.baidu.com
    http: https://www.baidu.com

  - name: qq
    http: http://www.qq.com
